apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: presenterte-kandidater-api
  namespace: toi
  labels:
    team: toi
spec:
  receivers:
    slack:
      channel: 'inkludering-alerts-prod'
  alerts:
    - alert: 'presenterte-kandidater-api'
      expr: sum(up{app="presenterte-kandidater-api", job="kubernetes-pods"}) == 0
      for: 1s
      description: "Appen er nede"
      action: "https://logs.adeo.no/app/r/s/J1BAt"

    - alert: 'presenterte-kandidater-api'
      expr: sum(increase(logd_messages_total{log_app="presenterte-kandidater-api",log_level="Error"}[10m])) > 0
      for: 10s
      description: "Appen har logget en feil"
      action: "https://logs.adeo.no/app/r/s/J1BAt"
