apiVersion: "nais.io/v1"
kind: "Alert"
metadata:
  name: presenterte-kandidater-api
  namespace: toi
  labels:
    team: toi
spec:
  receivers:
    slack:
      channel: 'inkludering-alerts-prod'
  alerts:
    - alert: 'presenterte-kandidater-api'
      expr: kube_deployment_status_replicas_available{deployment="presenterte-kandidater-api"} == 0
      for: 1s
      description: "Appen er nede"
      action: "https://logs.adeo.no/app/r/s/J1BAt"

    - alert: 'presenterte-kandidater-api'
      expr: sum(increase(logd_messages_total{log_app="presenterte-kandidater-api",log_level="Error"}[10m])) > 0
      for: 10s
      description: "Appen har logget en feil"
      action: "https://logs.adeo.no/app/r/s/J1BAt"

    - alert: 'presenterte-kandidater-api'
      severity: warning
      expr: (100 * sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="presenterte-kandidater-api",log_level=~"Warning"}[5m])) / sum by (log_app, log_namespace) (rate(logd_messages_total{log_app="presenterte-kandidater-api"}[5m]))) > 20
      for: 5m
      description: Økning i warnings
      action: "https://logs.adeo.no/app/r/s/J1BAt"
