apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: presenterte-kandidater-api
  namespace: toi
  labels:
    team: toi
spec:
  image: {{ image }}
  port: 9000
  ingresses:
  {{#each ingress as |url|}}
     - {{ url }}
  {{/each}}
  liveness:
    path: /isalive
  readiness:
    port: 8080
    path: /isready
  prometheus:
    enabled: true
    path: /internal/prometheus
    port: "9000"
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 3000m
      memory: 2048Mi
    requests:
      cpu: 200m
      memory: 512Mi
  secureLogs:
    enabled: true
  openSearch:
    access: read
    instance: kandidat
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: presenterte-kandidater
        - application: min-side-arbeidsgiver
          namespace: fager
    outbound:
      external:
        - host: {{ altinn_proxy_host }}
  kafka:
    pool: {{ kafka-pool }}
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        tier: {{ gcp_db_tier }}
        diskAutoresize: {{ gcp_disk_autoresize }}
        databases:
          - name: presenterte-kandidater-db
  env:
    - name: KAFKA_RAPID_TOPIC
      value: toi.rapid-1
    - name: KAFKA_CONSUMER_GROUP_ID
      value: {{ kafka_consumer_group_id }}
    - name: KAFKA_RESET_POLICY
      value: "latest"
    - name: ALTINN_PROXY_URL
      value: {{ altinn_proxy_url }}
    - name: ALTINN_PROXY_AUDIENCE
      value: {{ altinn_proxy_audience }}
